version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'container_stop_game_db'
    environment:
      - MONGO_INITDB_DATABASE=stop_game_db
      - MONGO_INITDB_ROOT_USERNAME=stop_game_db_user
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      #- ./init-mongo.js:docker-entrypoint-initdb.d/init-monogo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
